"use client"

import { LiveKitRoom } from "@livekit/components-react"
import type { TokenResponse } from "@meet/shared"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { DisconnectReason, setLogLevel } from "livekit-client"
import { useCallback, useEffect, useRef, useState } from "react"
import { toast } from "react-toastify"
import { Lobby } from "@/components/room/Lobby"
import { MeetingView } from "@/components/room/MeetingView"
import { WaitingRoom } from "@/components/room/WaitingRoom"
import { readVoiceIsolationPref } from "@/hooks/useVoiceIsolation"
import { clearRoomContext, setRoomContext, track } from "@/lib/analytics"
import { consumeExplicitLeave } from "@/lib/leaveIntent"
import { $channelRoom } from "@/stores/channelContext"
import { readDevicePref } from "@/stores/devicePrefs"
import { $isHost } from "@/stores/host"
import {
  $autoGain,
  $sendQuality,
  AUTO_RESOLUTION,
  SEND_QUALITY_RESOLUTION,
  type SendQuality,
} from "@/stores/preferences"
import { getRoomSnapshot, resetRoomSnapshot } from "@/stores/roomTelemetry"

const queryClient = new QueryClient()

// The stored rejoin proof is only trusted for a silent auto-join while the
// token behind it can still be valid — tokens carry a 1h TTL (see the token
// route). Past that, walking straight past the lobby would be pure bypass:
// the server would refuse the stale proof and mint a fresh identity anyway.
const REJOIN_MAX_AGE_MS = 60 * 60 * 1000
// A non-terminal disconnect retries the join at most this many times before
// giving up and landing back at the lobby.
const MAX_AUTO_REJOIN_ATTEMPTS = 3

/** User-facing message for a disconnect the user didn't confirm themselves. */
function involuntaryLeaveMessage(reason?: DisconnectReason): string | null {
  if (reason === undefined || reason === DisconnectReason.CLIENT_INITIATED) {
    return null
  }
  if (reason === DisconnectReason.PARTICIPANT_REMOVED) {
    return "You were removed from the meeting."
  }
  if (
    reason === DisconnectReason.ROOM_DELETED ||
    reason === DisconnectReason.ROOM_CLOSED
  ) {
    return "The meeting has ended."
  }
  return "You were disconnected from the meeting."
}

export type JoinPreferences = {
  displayName: string
  audioEnabled: boolean
  videoEnabled: boolean
  audioDeviceId?: string
  videoDeviceId?: string
}

export function RoomClient({
  slug,
  shareBase,
  mode = "meeting",
}: {
  slug: string
  shareBase?: string
  // Channel mode: same room UI, different join contract — the channel token
  // route never 425s and never returns waiting, so the start-gate and
  // waiting-room branches below simply never activate. Membership required:
  // a 401 sends the visitor through login instead of the guest lobby flow.
  mode?: "meeting" | "channel"
}) {
  // Surface connection diagnostics in the console; full debug via env flag.
  useEffect(() => {
    setLogLevel(process.env.NEXT_PUBLIC_LK_DEBUG === "1" ? "debug" : "info")
  }, [])

  const [session, setSession] = useState<{
    token: TokenResponse
    prefs: JoinPreferences
  } | null>(null)
  const [rejoining, setRejoining] = useState(false)
  const [admitted, setAdmitted] = useState(false)
  // Set when the meeting's creator hasn't arrived yet; holds the join
  // preferences so we can retry the same join until the meeting starts.
  const [awaitingStart, setAwaitingStart] = useState<JoinPreferences | null>(
    null,
  )
  // Older booked links carried the room's host key in the URL fragment;
  // current bookings get plain links (hosts claim with the management
  // password instead), but honor the fragment for links already sitting in
  // calendars. Stash it and scrub the address bar so it isn't shared onward
  // by copy-pasting the URL from the browser.
  useEffect(() => {
    try {
      const match = window.location.hash.match(/[#&]hk=([0-9a-f]{64})/)
      if (!match) return
      localStorage.setItem(`hostKey:${slug}`, match[1])
      history.replaceState(null, "", window.location.pathname)
    } catch {}
  }, [slug])

  // Groups every event from this meeting under one opaque id; the slug
  // itself never leaves the browser.
  useEffect(() => {
    setRoomContext(slug)
    resetRoomSnapshot()
    return () => clearRoomContext()
  }, [slug])

  // Channel sessions expose their room to the chat panel, which hydrates
  // and persists the channel's text sidecar.
  useEffect(() => {
    $channelRoom.set(mode === "channel" ? slug : null)
    return () => $channelRoom.set(null)
  }, [mode, slug])

  // The id of the current active period of the room, generated by the host
  // when the meeting starts and echoed on room_ended so a rejoined room
  // yields distinct started→ended pairs. Kept in sessionStorage so a page
  // refresh doesn't start a phantom second meeting.
  const meetingSessionRef = useRef<string | null>(null)
  const joinedAtRef = useRef<number | null>(null)
  const roleRef = useRef<"host" | "guest">("guest")
  const waitingSinceRef = useRef<number | null>(null)
  // Consecutive automatic rejoin attempts since the last successful join.
  const autoRejoinAttemptsRef = useRef(0)
  // The rejoin token this session last wrote to localStorage — terminal
  // cleanup compares against it so it only ever removes its own proof,
  // never one a newer tab (DUPLICATE_IDENTITY takeover) wrote after us.
  const lastRejoinTokenRef = useRef<string | null>(null)

  // Channel rooms mint tokens from the channel route (membership-gated, no
  // start gate); meetings keep theirs. Everything else in here is shared.
  const tokenEndpoint =
    mode === "channel"
      ? `/api/channels/${slug}/token`
      : `/api/rooms/${slug}/token`

  const handleJoin = useCallback(
    async (prefs: JoinPreferences, rejoinToken?: string) => {
      setAdmitted(false)
      let hostKey: string | undefined
      try {
        hostKey = localStorage.getItem(`hostKey:${slug}`) ?? undefined
      } catch {}
      try {
        const res = await fetch(tokenEndpoint, {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            displayName: prefs.displayName,
            rejoinToken,
            hostKey,
          }),
        })
        if (res.status === 401 && mode === "channel") {
          // Channels are members-only: route through login and back.
          window.location.href = `/auth/login?returnTo=${encodeURIComponent(
            window.location.pathname,
          )}`
          return
        }
        if (res.status === 404) {
          track("room_join_failed", { reason: "not_found" })
          toast.error(
            mode === "channel"
              ? "This channel doesn't exist (or you don't have access to it)."
              : "This meeting doesn't exist or has already ended. Ask for a fresh link.",
          )
          return
        }
        if (res.status === 425) {
          // The creator hasn't arrived; wait and keep retrying.
          setAwaitingStart(prefs)
          return
        }
        if (!res.ok) {
          track("room_join_failed", { reason: "server" })
          toast.error("Could not join the meeting. Please try again.")
          return
        }
        const token = (await res.json()) as TokenResponse
        setAwaitingStart(null)
        $isHost.set(token.isHost)
        if (token.hostKey) {
          try {
            localStorage.setItem(`hostKey:${slug}`, token.hostKey)
          } catch {}
        }
        roleRef.current = token.isHost ? "host" : "guest"
        try {
          // localStorage (not sessionStorage) so the proof survives closing
          // the tab, not just refreshing it.
          localStorage.setItem(
            `rejoin:${slug}`,
            // The token doubles as proof of admission on the next refresh;
            // savedAt bounds how long it's trusted for a silent auto-join.
            JSON.stringify({
              prefs,
              rejoinToken: token.token,
              savedAt: Date.now(),
            }),
          )
          lastRejoinTokenRef.current = token.token
        } catch {}
        autoRejoinAttemptsRef.current = 0
        // The host bounds the meeting: the server holds guests until the
        // creator arrives, so the host's fresh join is the start of an
        // active period. A refresh restores the stored id instead of
        // starting a new one.
        if (token.isHost && !token.waiting) {
          if (rejoinToken && !meetingSessionRef.current) {
            try {
              meetingSessionRef.current = sessionStorage.getItem(
                `msession:${slug}`,
              )
            } catch {}
          }
          if (!meetingSessionRef.current) {
            const sessionId = crypto.randomUUID()
            meetingSessionRef.current = sessionId
            try {
              sessionStorage.setItem(`msession:${slug}`, sessionId)
            } catch {}
            track("meeting_started", { room_session_id: sessionId })
          }
        }
        if (!token.waiting) {
          // Re-anchor the duration clock on every successful join — a rejoin
          // included, or the eventual real leave tracks no duration. Only a
          // genuinely new join fires room_joined; waiting-room entries are
          // counted on admission instead.
          joinedAtRef.current = Date.now()
          if (!rejoinToken) {
            track("room_joined", {
              role: token.isHost ? "host" : "guest",
              via_waiting_room: false,
            })
          }
        }
        // Knocking is its own funnel: the entry is paired with the
        // admission (or the abandonment) to show waiting-room drop-off.
        if (token.waiting && !waitingSinceRef.current) {
          waitingSinceRef.current = Date.now()
          track("waiting_room_entered")
        }
        setSession({ token, prefs })
      } catch {
        track("room_join_failed", { reason: "network" })
        toast.error("Could not join the meeting. Please try again.")
      }
    },
    [slug, mode, tokenEndpoint],
  )

  // A refresh rejoins the meeting automatically; only an explicit leave (or a
  // server-side disconnect) drops back to the lobby.
  useEffect(() => {
    let stored: {
      prefs: JoinPreferences
      rejoinToken?: string
      savedAt?: number
    } | null = null
    try {
      const raw = localStorage.getItem(`rejoin:${slug}`)
      if (raw) {
        const parsed = JSON.parse(raw)
        // Older entries stored the preferences at the top level.
        stored = parsed.prefs
          ? parsed
          : { prefs: parsed as JoinPreferences, rejoinToken: undefined }
      }
    } catch {}
    if (!stored?.prefs?.displayName) return
    // Only a fresh proof auto-joins; a stale one (or an older entry without
    // savedAt) falls through to the lobby like any first visit.
    const savedAt = stored.savedAt
    if (typeof savedAt !== "number" || Date.now() - savedAt > REJOIN_MAX_AGE_MS)
      return
    setRejoining(true)
    handleJoin(stored.prefs, stored.rejoinToken).finally(() =>
      setRejoining(false),
    )
  }, [slug, handleJoin])

  // Background token renewal (on admission and the periodic refresh below)
  // used to swallow failures silently, leaving no signal before the stored
  // proof expired mid-meeting. Warn once a couple of consecutive attempts
  // have failed rather than on the first blip.
  const refreshFailCountRef = useRef(0)
  const noteRefreshFailure = useCallback(() => {
    refreshFailCountRef.current += 1
    if (refreshFailCountRef.current < 2) return
    if (toast.isActive(`refresh-fail:${slug}`)) return
    toast.error(
      "Having trouble renewing your connection — you may be disconnected soon. Try reloading if this continues.",
      { toastId: `refresh-fail:${slug}` },
    )
  }, [slug])

  // On admission, swap the stored waiting token for an admitted one while
  // the server can still see us connected as human — so a later refresh
  // walks straight in instead of knocking again.
  const handleAdmitted = useCallback(() => {
    setAdmitted(true)
    joinedAtRef.current = Date.now()
    if (waitingSinceRef.current) {
      track("waiting_room_admitted", {
        waited_seconds: Math.round(
          (Date.now() - waitingSinceRef.current) / 1000,
        ),
      })
      waitingSinceRef.current = null
    }
    track("room_joined", { role: "guest", via_waiting_room: true })
    const current = localStorage.getItem(`rejoin:${slug}`)
    if (!current) return
    try {
      const stored = JSON.parse(current) as {
        prefs: JoinPreferences
        rejoinToken?: string
      }
      void fetch(`/api/rooms/${slug}/token`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          displayName: stored.prefs.displayName,
          rejoinToken: stored.rejoinToken,
          // Without this the server can't tell this apart from a brand-new
          // joiner and mints a fresh identity that was never connected —
          // this participant's own admit/moderate calls would then 403
          // against the still-live LiveKit participant under the old
          // identity (issue #192).
          refresh: true,
        }),
      })
        .then((res) => (res.ok ? res.json() : null))
        .then((fresh: TokenResponse | null) => {
          if (fresh && !fresh.waiting) {
            localStorage.setItem(
              `rejoin:${slug}`,
              JSON.stringify({
                prefs: stored.prefs,
                rejoinToken: fresh.token,
                savedAt: Date.now(),
              }),
            )
            lastRejoinTokenRef.current = fresh.token
            refreshFailCountRef.current = 0
          } else {
            noteRefreshFailure()
          }
        })
        .catch(() => noteRefreshFailure())
    } catch {}
  }, [slug, noteRefreshFailure])

  // Tokens expire after an hour, and room-scoped API routes (agent invites,
  // admit, doc) authenticate with the stored one — so a meeting running past
  // the TTL strands those calls with 401s while the WebRTC session carries on
  // fine. Renew the proof in the background well before it lapses; the server
  // keeps the same identity for a verified refresh.
  useEffect(() => {
    if (!session) return
    const timer = setInterval(
      () => {
        try {
          const raw = localStorage.getItem(`rejoin:${slug}`)
          if (!raw) return
          const stored = JSON.parse(raw) as {
            prefs: JoinPreferences
            rejoinToken?: string
          }
          if (!stored.rejoinToken) return
          void fetch(tokenEndpoint, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({
              displayName: stored.prefs.displayName,
              rejoinToken: stored.rejoinToken,
              refresh: true,
            }),
          })
            .then((res) => (res.ok ? res.json() : null))
            .then((fresh: TokenResponse | null) => {
              // Never downgrade a good token to a "waiting" one: a failed
              // refresh leaves the old proof in place until it expires.
              if (fresh && !fresh.waiting) {
                localStorage.setItem(
                  `rejoin:${slug}`,
                  JSON.stringify({
                    prefs: stored.prefs,
                    rejoinToken: fresh.token,
                    savedAt: Date.now(),
                  }),
                )
                lastRejoinTokenRef.current = fresh.token
                refreshFailCountRef.current = 0
              } else {
                noteRefreshFailure()
              }
            })
            .catch(() => noteRefreshFailure())
        } catch {}
      },
      40 * 60 * 1000,
    )
    return () => clearInterval(timer)
  }, [session, slug, tokenEndpoint, noteRefreshFailure])

  // A disconnect fires for an explicit "Leave", a transient network drop, AND
  // a page reload/tab close — LiveKit calls disconnect() on both
  // beforeunload and pagehide, so those report the exact same
  // DisconnectReason.CLIENT_INITIATED as clicking Leave. The reason alone
  // can't tell a real leave from the browser tearing the page down, so
  // CLIENT_INITIATED only counts as terminal when the Leave button marked
  // its intent first (see lib/leaveIntent). Reasons the server itself
  // decided (kicked, superseded, room gone) are always terminal.
  const TERMINAL_DISCONNECT_REASONS = useRef(
    new Set([
      DisconnectReason.DUPLICATE_IDENTITY,
      DisconnectReason.PARTICIPANT_REMOVED,
      DisconnectReason.ROOM_DELETED,
    ]),
  ).current
  const handleDisconnected = useCallback(
    (reason?: DisconnectReason) => {
      // Giving up while still knocking is the other half of the waiting-room
      // funnel — without it an abandoned knock looks like nothing happened.
      if (waitingSinceRef.current) {
        track("waiting_room_abandoned", {
          waited_seconds: Math.round(
            (Date.now() - waitingSinceRef.current) / 1000,
          ),
        })
        waitingSinceRef.current = null
      }
      if (joinedAtRef.current) {
        const duration = Math.round((Date.now() - joinedAtRef.current) / 1000)
        const stats = getRoomSnapshot()
        track("room_left", {
          duration_seconds: duration,
          participant_count: stats.participantCount,
          had_ai_agent: stats.hadAgent,
          role: roleRef.current,
        })
        // The room closing is one event, not one per participant: the host
        // reports it, and only when nobody is left behind. (A room the server
        // reaps after everyone's browser is gone produces nothing — that needs
        // a LiveKit webhook, which this deployment doesn't have yet.)
        if (roleRef.current === "host" && stats.participantCount <= 1) {
          track("room_ended", {
            room_session_id: meetingSessionRef.current ?? "unknown",
            participant_count: stats.participantCount,
            peak_participant_count: stats.peakParticipantCount,
            duration_seconds: duration,
            had_ai_agent: stats.hadAgent,
            agent_count: stats.agentTypes.length,
          })
          for (const agentType of stats.agentTypes) {
            track("agent_removed", {
              agent_type: agentType,
              reason: "call_ended",
            })
          }
        }
        joinedAtRef.current = null
      }
      resetRoomSnapshot()
      setSession(null)
      const isExplicitLeave =
        reason === DisconnectReason.CLIENT_INITIATED && consumeExplicitLeave()
      if (
        isExplicitLeave ||
        (reason !== undefined && TERMINAL_DISCONNECT_REASONS.has(reason))
      ) {
        // Clear the stored proof — but only if it's still the one this
        // session wrote last. On DUPLICATE_IDENTITY another tab has taken
        // over the identity and already saved its own fresher proof;
        // deleting that here would log the live tab out on its next refresh.
        try {
          const raw = localStorage.getItem(`rejoin:${slug}`)
          if (raw) {
            const stored = JSON.parse(raw) as { rejoinToken?: string }
            if (
              !stored.rejoinToken ||
              stored.rejoinToken === lastRejoinTokenRef.current
            ) {
              localStorage.removeItem(`rejoin:${slug}`)
            }
          }
        } catch {}
        // The meeting session ends only on a real leave — an auto-rejoin
        // below continues the same active period.
        meetingSessionRef.current = null
        try {
          sessionStorage.removeItem(`msession:${slug}`)
        } catch {}
        const involuntaryMessage = involuntaryLeaveMessage(reason)
        if (involuntaryMessage) toast.info(involuntaryMessage)
        return
      }
      // Anything else (network drop, failed reconnect) auto-rejoins with the
      // stored proof — but bounded: a persistent failure must land back at
      // the lobby, not spin forever against a dead server. The counter
      // resets on a join that actually succeeds (see handleJoin).
      if (autoRejoinAttemptsRef.current >= MAX_AUTO_REJOIN_ATTEMPTS) {
        meetingSessionRef.current = null
        try {
          sessionStorage.removeItem(`msession:${slug}`)
        } catch {}
        const involuntaryMessage = involuntaryLeaveMessage(reason)
        if (involuntaryMessage) toast.info(involuntaryMessage)
        return
      }
      try {
        const raw = localStorage.getItem(`rejoin:${slug}`)
        if (!raw) return
        const stored = JSON.parse(raw) as {
          prefs: JoinPreferences
          rejoinToken?: string
        }
        autoRejoinAttemptsRef.current += 1
        // Show "Rejoining…" (not the lobby) while the automatic attempt is
        // in flight, so a racing manual Join can't double-connect. Each
        // retry backs off a little longer than the last.
        setRejoining(true)
        window.setTimeout(
          () => {
            void handleJoin(stored.prefs, stored.rejoinToken).finally(() =>
              setRejoining(false),
            )
          },
          (autoRejoinAttemptsRef.current - 1) * 2000,
        )
      } catch {}
    },
    [slug, handleJoin, TERMINAL_DISCONNECT_REASONS],
  )

  // Poll while the meeting hasn't started; the successful join clears this.
  useEffect(() => {
    if (!awaitingStart || session) return
    const timer = setInterval(() => void handleJoin(awaitingStart), 5000)
    return () => clearInterval(timer)
  }, [awaitingStart, session, handleJoin])

  if (awaitingStart && !session) {
    // No unauthenticated "start anyway" — it let anyone with the link open
    // (and take over) a meeting before its real host arrived. Starting takes
    // the host key (creator's browser) or the management password, exchanged
    // below for this room's key.
    return (
      <main className="flex min-h-full flex-col items-center justify-center gap-3 px-6 text-center">
        <p className="animate-pulse font-medium text-lg">
          This meeting hasn't started yet
        </p>
        <p className="text-base-content/60 text-sm">
          You'll join automatically once the host arrives.
        </p>
        <ClaimHost
          slug={slug}
          onClaimed={() => void handleJoin(awaitingStart)}
        />
      </main>
    )
  }

  if (rejoining) {
    return (
      <main className="flex min-h-full items-center justify-center gap-3">
        <span className="loading loading-spinner" />
        Rejoining…
      </main>
    )
  }

  if (!session) {
    return <Lobby slug={slug} onJoin={handleJoin} />
  }

  const inWaitingRoom = session.token.waiting && !admitted

  // Phone-sized screens capture portrait video (9:16) — LiveKit's default
  // capture presets are landscape, which is what makes a phone's camera
  // publish a sideways-looking track. Applied as the room's capture default
  // so later camera toggles inherit it too.
  const portraitCapture =
    typeof window !== "undefined" &&
    window.matchMedia("(max-width: 639px)").matches

  // Seed LiveKit's active device with the chosen input (the lobby writes the
  // same pref useStickyDevices reads). Setting it here means the very first
  // captured track — and every unmute after — uses the picked device rather
  // than the OS default. An empty pref leaves LiveKit on the system default.
  const audioDeviceId =
    session.prefs.audioDeviceId || readDevicePref("audioinput") || undefined
  const videoDeviceId =
    session.prefs.videoDeviceId || readDevicePref("videoinput") || undefined

  return (
    <LiveKitRoom
      token={session.token.token}
      serverUrl={session.token.serverUrl}
      options={{
        // Auto quality adapts to network conditions: simulcast publishes
        // layered resolutions, dynacast pauses layers nobody is consuming,
        // and adaptiveStream sizes what we receive to what's on screen.
        // Congestion control then walks the send bitrate up and down.
        dynacast: true,
        adaptiveStream: true,
        // Keep the browser DSP on and layer enhanced voice isolation on top
        // per the saved preference; where unsupported the extra flag is simply
        // ignored. Set as a capture default so unmuting inherits it too.
        audioCaptureDefaults: {
          deviceId: audioDeviceId,
          voiceIsolation: readVoiceIsolationPref(),
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: $autoGain.get(),
        },
        videoCaptureDefaults: {
          deviceId: videoDeviceId,
          // Send-quality cap wins over the portrait default: it exists for
          // uplink-poor connections, which phones often are. "auto" captures
          // 1080p; what actually goes out adapts to the network (simulcast
          // layers + congestion control, dynacast below).
          ...($sendQuality.get() !== "auto"
            ? {
                resolution:
                  SEND_QUALITY_RESOLUTION[
                    $sendQuality.get() as Exclude<SendQuality, "auto">
                  ],
              }
            : portraitCapture
              ? { resolution: { width: 720, height: 1280 } }
              : { resolution: AUTO_RESOLUTION }),
        },
      }}
      // Waiting participants join without media; on admission WaitingRoom
      // brings devices up per the lobby preferences. Otherwise join with the
      // lobby's mic setting — unless others are already in the call, in
      // which case join muted (unmute from the control bar).
      audio={
        !session.token.waiting &&
        session.prefs.audioEnabled &&
        session.token.participantCount === 0 && {
          deviceId: session.prefs.audioDeviceId,
        }
      }
      video={
        !session.token.waiting &&
        session.prefs.videoEnabled && {
          deviceId: session.prefs.videoDeviceId,
        }
      }
      onDisconnected={handleDisconnected}
      onError={(err) => {
        toast.error(
          `Could not connect to the meeting server (${err.message}). ` +
            "Check that the LiveKit server is running and reachable.",
        )
      }}
      className="h-full"
    >
      <QueryClientProvider client={queryClient}>
        {inWaitingRoom ? (
          <WaitingRoom prefs={session.prefs} onAdmitted={handleAdmitted} />
        ) : (
          <MeetingView
            slug={slug}
            shareBase={shareBase}
            startedAt={session.token.roomStartedAt}
          />
        )}
      </QueryClientProvider>
    </LiveKitRoom>
  )
}

/**
 * "I'm the host": exchange the deployment's management password for this
 * room's host key. The password crosses the wire once; the browser keeps
 * the per-room key every host-gated route understands. This is how booked
 * meetings (plain links, no creator browser) get their host — and how a
 * host on a new device, or a colleague covering for them, takes over.
 */
function ClaimHost({
  slug,
  onClaimed,
}: {
  slug: string
  onClaimed: () => void
}) {
  const [open, setOpen] = useState(false)
  const [password, setPassword] = useState("")
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  if (!open) {
    return (
      <button
        type="button"
        className="btn btn-outline btn-sm"
        onClick={() => setOpen(true)}
      >
        I'm the host — start the meeting
      </button>
    )
  }

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    setBusy(true)
    setError(null)
    try {
      const res = await fetch(`/api/rooms/${slug}/claim-host`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ password }),
      })
      const data = (await res.json().catch(() => ({}))) as {
        hostKey?: string
        error?: string
      }
      if (!res.ok || !data.hostKey) {
        setError(data.error ?? "could not claim host")
        return
      }
      try {
        localStorage.setItem(`hostKey:${slug}`, data.hostKey)
      } catch {}
      onClaimed()
    } catch {
      setError("network error — try again")
    } finally {
      setBusy(false)
    }
  }

  return (
    <form onSubmit={submit} className="flex items-center gap-2">
      <input
        autoFocus
        type="password"
        className="input input-sm"
        placeholder="Management password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        aria-label="Management password"
      />
      <button
        type="submit"
        className="btn btn-primary btn-sm"
        disabled={busy || !password}
      >
        {busy && <span className="loading loading-spinner loading-xs" />}
        Start
      </button>
      {error && <span className="text-error text-xs">{error}</span>}
    </form>
  )
}
